translation file: scoped package
TWNTF/Translations pull request #5
Opened 2018-08-20 02:44 UTC by yqxiaxia

2018-08-21 02:51 UTC, wtzeng1 commented on docs/npm-package/docs/package_scope/README.md
> +域（scopes）通常就是将相关的 package 进行分组，然后分别创建命名空间去管理，就像是为这些 package 创建了一个域。更多关于 npm 域的定义可以查看[npm scopes](https://docs.npmjs.com/misc/scope)。
> Scopes are used to group related packages together

我觉得原文中的"are used to"在这里翻译为"被用作/被用于"更合适一些

2018-08-23 05:45 UTC, MrFatt requested changes

2018-08-23 05:45 UTC, MrFatt commented on docs/npm-package/docs/package_scope/README.md
> +默认情况下，scoped package 是私有的，如果想要发布私有的包，你需要付费用户。
需要`是`付费用户

2018-08-23 06:17 UTC, MrFatt approved these changes

2018-08-23 09:51 UTC, jtsang4 approved these changes

2018-08-23 15:11 UTC, merged